### PR TITLE
Linux snap package

### PR DESCRIPTION
**Pull request by versus**
I propose  another popular way to create a Linux package for pingme aka snap package  (https://snapcraft.io) 
Also, I think you have to create a developer account in snapcraft and upload pingme.

### CODE REVIEW

**Comment by kha7iq** [comment]
Hello @versus Thank you again for working on this.
At the moment there is not alot for requirements for snap or docker images, and also there is an option to automatically build snaps/docker image with goreleaser used for release management.
Please always open an issue first as per contributing guide lines so that we can discuss which features can be implemented.
As always i appreciate your contribution.

**Comment by versus** [comment]
I created it for me. I'm devops engineer and use pingme for pipelines, build servers and github actions. 
So, I need docker and snap package and share them for you. 

Thanks for good tool.

**Comment by kha7iq** [comment]
Thank you @versus 
I will let you know about docker support.

**Comment by kha7iq** [comment]
@versus 
https://github.com/kha7iq/pingme/blob/master/.goreleaser.yaml#L71
Snap configuration for release is added but disabled at the moment, If you consider this important you can enable and test it locally after that you are most welcome to open a new pull request.
Thank you

**Pull request closed without merging**
