### PR TITLE
Add pushover service

### PR DESCRIPTION
**Pull request by versus**
Add pushover service

### CODE REVIEW

**Comment by kha7iq** [comment]
Thank you @versus this looks very good now.
Can you please make a small change to main.go and pusover.go file
pushover.go
```
// slackPingMe struct holds data parsed via flags for slack service.
can you replace struct name here with pushOver, and also replace `slack` with pushover

token usage
Usage:       "Token of pushover application is used for authenticating application.",
```
main.go
Add push over service in description so that it appears in help menu of app.
```
app.Description = `PingMe is a CLI tool which provides the ability to send messages or alerts to multiple 
messaging platforms and also email, everything is configurable via environment
variables and command line switches. Currently supported platforms include Slack, Telegram,
RocketChat, Discord, Pushover, Microsoft Teams and email address.`

```

Just make the changes and commit to your repo, everything else looks great.
you can use the commit message fix
git commit -m "fix: your message" 
And push to your branch

**Comment by kha7iq** [comment]
PR connects to https://github.com/kha7iq/pingme/issues/3

**Comment by versus** [comment]
thanks for advices

**Review by kha7iq — APPROVED** [review]
Approved

**Pull request merged**
